config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  
  root to: "pages#home"

  resources :messages, except: [:edit, :update]
  get '/sent' => 'messages#sent'

  get '/colorcrush' => 'pages#colorcrush'
  get '/jieyisushi' => 'pages#jieyisushi'
  get '/sparkstart' => 'pages#sparkstart'
  get '/buymenow' => 'pages#buymenow'
  get '/paramount' => 'pages#paramount'

  resources :posts
  get '/blog' => 'posts#index'
  get '/blog/archive' => 'posts#archive'
  get '/blog/drafts' => 'posts#drafts'

  resources :comments, except: [:show, :edit]
  
  get '/v1' => 'home#v1'

  namespace :v1 do
    root to: "home#index"
  end

end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  has_many :categorized_posts
  has_many :categories, through: :categorized_posts

  has_many :tagged_posts
  has_many :tags, through: :tagged_posts

  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy, :drafts]

  def index
    # posts = Post.where(published: true)
    @posts = Post.where(published: true).order(:created_at).reverse.take(10)

    @search = params[:search]
    @tag_search = params[:tag_search]
    @category_search = params[:category_search]

    @searched = posts.where("title ILIKE ? OR body ILIKE ?", "%#{@search}%", "%#{@search}%") if @search.blank? == false
    @searched = Tag.find_by(tag_name: @tag_search).posts if @tag_search.blank? == false
    @searched = Category.find_by(category_name: @category_search).posts if @category_search.blank? == false
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @category_list = @post.categories.collect { |category| category.category_name }
    @tag_list = @post.tags.collect { |tag| tag.tag_name }
    @approved_comments = @post.comments.where(approved: true).order(id: :asc)
  end

  def archive
    @posts = Post.where(published: true).order(:created_at).reverse
    @categories = Category.all.collect { |category| category.category_name }
    @tags = Tag.all.collect { |tag| tag.tag_name }
  end

  def drafts
    @drafts = Post.where(published: false).order(:created_at).reverse
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      @category_string = params[:category_string]
      @category_string_split = @category_string.split(", ")
      @category_string_split.each do |category|
        category = category.strip
        if !Category.find_by(category_name: category)
          @new_category = Category.create(category_name: category)
          CategorizedPost.create(
            post_id: @post.id,
            category_id: @new_category.id
          )
        else
          @category_id = Category.find_by(category_name: category)
          CategorizedPost.create(
            post_id: @post.id,
            category_id: @category_id.id
          )
        end
      end

      @tag_string = params[:tag_string]
      @tag_string_split = @tag_string.split(", ")
      @tag_string_split.each do |tag|
        tag = tag.strip
        if !Tag.find_by(tag_name: tag)
          @new_tag = Tag.create(tag_name: tag)
          TaggedPost.create(
            post_id: @post.id,
            tag_id: @new_tag.id
          )
        else
          @tag_id = Tag.find_by(tag_name: tag)
          TaggedPost.create(
            post_id: @post.id,
            tag_id: @tag_id.id
          )
        end
      end

      flash[:success] = "Post created."
      redirect_to "/posts/#{@post.id}"
    else
      flash[:alert] = @post.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @post_categories = @post.categories.collect { |category| category.category_name }
    @category_string = @post_categories.join(", ")
    @post_tags = @post.tags.collect { |tag| tag.tag_name }
    @tag_string = @post_tags.join(", ")
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      @post.categorized_posts.each { |post| post.delete }
      @category_string = params[:category_string]
      @category_string_split = @category_string.split(", ")
      @category_string_split.each do |category|
        category = category.strip
        if !Category.find_by(category_name: category)
          @new_category = Category.create(category_name: category)
          CategorizedPost.create(
            post_id: @post.id,
            category_id: @new_category.id
          )
        else
          @category_id = Category.find_by(category_name: category)
          CategorizedPost.create(
            category_id: @category_id.id,
            post_id: @post.id
          )
        end
      end

      @post.tagged_posts.each { |post| post.delete }
      @tag_string = params[:tag_string]
      @tag_string_split = @tag_string.split(", ")
      @tag_string_split.each do |tag|
        tag = tag.strip
        if !Tag.find_by(tag_name: tag)
          @new_tag = Tag.create(tag_name: tag)
          TaggedPost.create(
            post_id: @post.id,
            tag_id: @new_tag.id
          )
        else
          @tag_id = Tag.find_by(tag_name: tag)
          TaggedPost.create(
            tag_id: @tag_id.id,
            post_id: @post.id
          )
        end
      end

      flash[:success] = "Post updated."
      redirect_to "/posts/#{@post.id}"
    else
      flash[:alert] = @post.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to '/blog'
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :published)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/archive.html.erb
<% title "a.chan blog | archive" %>
<% meta_description 'amy chan blog' %>

<div class="page-container">
  <div class="row">
    <div class="col l6 m12 s12 offset-l3">

      <div class="row">
        <div class="col l11 m11 s11">
          <%= form_tag "/blog", method: :get do %>
            <%= text_field_tag :search, nil, placeholder: "Search blog" %>
        </div>
        <div class="col l1 m1 s1">
            <%= button_tag(type: 'submit', class: 'waves-effect waves-light btn-flat', style: 'padding: 0') do %><i class="material-icons right">send &nbsp; </i><% end %>
          <% end %>
        </div>
      </div>

      <h4 class="center">View All Posts</h4>
      <br>

      <% if @posts.count > 0 %>
        <% @posts.each do |post| %>
          <p>
            <%= post.created_at.strftime("%m/%d/%Y") %>:
            <a href="/posts/<%= post.id %>"><%= post.title %></a>
          </p>
        <% end %>
      <% else %>
        <p>There are no posts yet.</p>
      <% end %>

      <br><hr><br>

      <h4 class="center">View All Categories</h4>
      
      <br>
      <div class="center">
        <% @categories.each do |category| %>
          <%= link_to category, "/blog/?category_search=#{category}" %>
        <% end %>
      </div>
      <br>

      <br><hr><br>

      <h4 class="center">View All Tags</h4>
      
      <br>
      <div class="center">
        <% @tags.each do |tag| %>
          <%= link_to tag, "/blog/?tag_search=#{tag}" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/posts/drafts.html.erb
<div class="page-container">
  <div class="row">
    <div class="col l6 m12 s12 offset-l3">
      <h4 class="center">View All Drafts</h4>
      <br>

      <% if @drafts.count > 0 %>
        <% @drafts.each do |draft| %>
          <p>
            <%= draft.created_at.strftime("%m/%d/%Y") %>:
            <a href="/posts/<%= draft.id %>/edit"><%= draft.title %></a>
          </p>
        <% end %>
      <% else %>
        <p>There are no drafts.</p>
      <% end %>

    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="page-container">
  <div class="row">
    <div class="col l6 m12 s12 offset-l3">
      <br>
      <div class="headline center">Edit Post</div>
      <br>

      <div class="center red-text">
        <% if alert %>
          <p><%= alert %></p>
          <br>
        <% end %>
      </div>

      <%= form_for @post do |f| %>
        <%= f.label :title, class: 'active' %>
        <%= f.text_field :title, class: 'validate' %>

        <%= f.label :body, class: 'active' %>
        <%= f.text_area :body, class: 'materialize-textarea validate' %>

        <%= label_tag :categories, nil, class: 'active' %>
        <%= text_field_tag :category_string, @category_string %>

        <%= label_tag :tags, nil, class: 'active' %>
        <%= text_field_tag :tag_string, @tag_string %>

        <%= f.label :published, class: 'active' %>
        <%= f.text_field :published, class: 'validate' %>

        <%= f.submit 'Update', class: 'waves-effect waves-light btn' %>
      <% end %>

    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% title "a.chan | blog" %>
<% meta_description 'amy chan blog' %>

<div class="page-container">
  <div class="row">
    <div class="col l6 m12 s12 offset-l3">
      <div class="center green-text">
        <% if notice %>
          <p><%= notice %></p> <br>
        <% end %>
      </div>
      
      <div class="row">
        <div class="col l7 m6 s12" style="padding: 0">
          <h4>Blog</h4>
          <% if admin_signed_in? && current_admin.superadmin %>
            <p>
              <a href="/posts/new">New Post</a> <br>
              <a href="/blog/drafts">View Drafts</a>
            </p>
          <% end %>
        </div>
        <div class="col l4 m5 s10" style="padding: 0">
          <% if @posts.count > 0 %>
            <%= form_tag "/blog", method: :get do %>
              <%= text_field_tag :search, nil, placeholder: "Search blog" %>
        </div>
        <div class="col l1 m1 s2">
            <%= button_tag(type: 'submit', class: 'waves-effect waves-light btn-flat', style: 'padding: 0') do %><i class="material-icons right">send &nbsp; </i><% end %>
            <% end %>
          <% end %>
        </div>
      </div>

      <% if !@searched %>
        <% if @posts.count > 0 %>
          <% @posts.each do |post| %>
            <br>
            <p>
              <a href="/posts/<%= post.id %>" class="headline"><%= post.title %></a>
              <br>
              <i><%= post.created_at.strftime("%B %e, %Y") %></i>
              <br>
            </p>
            <p>
              <%= sanitize(post.body.first(450)) %>
              <% if post.body.length > 450 %>
                ... <a href="/posts/<%= post.id %>">Read more</a>
              <% end %>
            </p>
            <p>
              <% category_list = post.categories.collect { |category| category.category_name } %>
              <% if category_list.length > 0 %>
                Categories: 
                <% category_list.each do |category| %>
                  <%= link_to category, "/blog/?category_search=#{category}" %><% if category_list.index(category) < category_list.length - 1 %>,<% end %>
                <% end %>
              <% end %>

              <% tag_list = post.tags.collect { |tag| tag.tag_name } %>
              <% if tag_list.length > 0 %>
                Tags: 
                <% tag_list.each do |tag| %>
                  <%= link_to tag, "/blog/?tag_search=#{tag}" %><% if tag_list.index(tag) < tag_list.length - 1 %>,<% end %>
                <% end %>
                <br>
              <% end %>
            </p>
            <br>
            <% if @posts.index(post) < @posts.length - 1 %>
              <hr>
            <% end %>
          <% end %>
        <% else %>
          <p>There are no posts yet.</p>
        <% end %>
      <% else %>
        <% if @searched.length > 0 %>
          <% @searched.each do |post| %>
            <br>
            <p>
              <a href="/posts/<%= post.id %>" class="headline"><%= post.title %></a>
              <br>
              <i><%= post.created_at.strftime("%B %e, %Y") %></i>
            </p>
            <p>
              <%= sanitize(post.body.first(450)) %>
              <% if post.body.length > 450 %>
                ... <a href="/posts/<%= post.id %>">Read more</a>
              <% end %>
            </p>
            <br>
            <hr>
          <% end %>
        <% else %>
          <p>No results.</p>
        <% end %>
      <% end %>
      
      <% if @posts.count > 0 %>
          <p class="right"><%= link_to 'See all posts >', "/blog/archive" %></p>
      <% end %>

    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="page-container">
  <div class="row">
    <div class="col l6 m12 s12 offset-l3">
      <br>
      <div class="headline center">New Post</div>
      <br>

      <div class="center red-text">
        <% if alert %>
          <p><%= alert %></p>
          <br>
        <% end %>
      </div>

      <%= form_for @post do |f| %>
        <%= f.label :title, class: 'active' %>
        <%= f.text_field :title, class: 'validate' %>
        
        <a id="info-toggle"><i class="material-icons">info_outline</i></a><br>
        <div id="blog-tips" class="hidden">
          <pre><code class="language-html">&lt;pre>&lt;code class="language-ruby"> insert code here &lt;/code>&lt;/pre></code></pre>
          <pre><code class="language-html">Use &amp;lt; (&lt;) to escape html tags</code></pre><br>
        </div>

        <%= f.label :body, class: 'active' %>
        <%= f.text_area :body, class: 'materialize-textarea validate' %>

        <%= label_tag :categories, nil, class: 'active' %>
        <%= text_field_tag :category_string %>

        <%= label_tag :tags, nil, class: 'active' %>
        <%= text_field_tag :tag_string %>

        <%= f.label :published, nil, class: 'active' %>
        <%= f.text_field :published %>

        <%= f.submit 'Save', class: 'waves-effect waves-light btn' %>
      <% end %>

    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% title "a.chan blog | #{@post.title}" %>
<% meta_description 'amy chan blog' %>

<div class="page-container">
  <div class="row">
    <div class="col l6 m12 s12 offset-l3">
      <p><a href="/blog">< Back to blog</a></p>

      <div class="center green-text">
        <% if notice %>
          <p><%= notice %></p> <br>
        <% end %>
      </div>

      <div class="blog-post">
        <p class="headline center"><%= @post.title %></p>

        <p class="post-body"><%= sanitize(@post.body) %></p>
        
        <p class="category-box">
          <% if @category_list.length > 0 %>
              <b>Categories:</b>
              <% @category_list.each do |category| %>
                <%= link_to category, "/blog/?category_search=#{category}" %><% if @category_list.index(category) < @category_list.length - 1 %>,<% end %>
              <% end %>
          <% end %>
        </p>
        
        <p class="tag-box">
          <% if @tag_list.length > 0 %>
              <b>Tags:</b>
              <% @tag_list.each do |tag| %>
                <%= link_to tag, "/blog/?tag_search=#{tag}" %><% if @tag_list.index(tag) < @tag_list.length - 1 %>,<% end %>
              <% end %>
          <% end %>
        </p>
      </div>

      <% if admin_signed_in? && current_admin.superadmin %>
        <p class="edit-link"><a href="/posts/<%= @post.id %>/edit">Edit Post</a></p>
      <% end %>

      <% if @approved_comments.size > 0 %>
        <p class="headline">Comments (<%= @approved_comments.size %>)</p>
        
        <div class="comments">
          <% @approved_comments.each do |comment| %>
            <div class="comment">
              <span class="lighter-text">Name:</span> <%= comment.commenter %><br>
              <% if comment.url.present? %>
                <span class="lighter-text">Website/Blog:</span> <a href="<%= comment.url %>"><%= comment.url %></a><br>
              <% end %>
              <span class="lighter-text">Comment:</span> <%= comment.body %>
            </div>
          <% end %>
        </div>
      <% end %>
      
      <div class="comment-form">
        <p class="headline">Leave a comment</p>

        <div class="red-text">
          <% if alert %>
            <p><%= alert %></p>
          <% end %>
        </div>

        <%= form_for @comment do |f| %>
          <%= f.invisible_captcha :subtitle %>
          
          <div class="input-field">
            <%= f.label :commenter, "Name (required)", class: 'active' %>
            <%= f.text_field :commenter, class: 'validate' %>
          </div>
          
          <div class="input-field">
            <%= f.label :email, "Email (required, will not be published)", class: 'active' %>
            <%= f.email_field :email, class: 'validate' %>
          </div>

          <div class="input-field">
            <%= f.label :url, "Website or blog (optional)", class: 'active' %>
            <%= f.text_field :url, class: 'validate' %>
          </div>

          <div class="input-field">
            <%= f.label :body, "Comment (required)", class: 'active' %>
            <%= f.text_area :body, class: 'materialize-textarea validate' %>
          </div>
          
          <%= f.hidden_field :post_id, value: @post.id %>
          <%= f.submit 'Submit', class: 'waves-effect waves-light btn' %>

        <% end %>
      </div>

    </div>
  </div>
</div>